### ISSUE TITLE
Would it be possible to generalize to any grammar available?

### ISSUE THREAD

**Issue by ag91** [Giedriusj1/helm-tree-sitter#1]
Hello there! This package idea is wonderful, thanks for the effort to make it real.
I was planning to do something similar. I like also the effort for the UX: labelling nodes to make them uniform to serch.
Any chance you could add an extra source that just displays `node_id: node text`?
I think it would be nice to use that instead of getting the error `Major mode not supported`.
What do you think?

**Comment by ag91** [comment]
actually this is roughly what I mean:
```
(helm :sources
      (helm-build-sync-source "Tree-sitter"
        :candidates (--map
                     (cons
                      (concat
                       (symbol-name (helm-tree-sitter-core-elem-node-type it))
                       " -- "
                       (s-truncate 30 (s-replace "\n" " " (helm-tree-sitter-core-elem-node-text it))))
                      it)
                     (helm-tree-sitter-core-build-node-list (tsc-root-node tree-sitter-tree) 0))
        :action (lambda (x)
                  (goto-char (helm-tree-sitter-core-elem-start-pos x)))
        :fuzzy-match t)
      :candidate-number-limit 9999
      :buffer "*helm tree-sitter*")
```
It's missing your nice italic and filling but this would be the ideal default for me when you didn't provide a prettifier

**Comment by Giedriusj1** [comment]
Hey there!

When I started working on this, my initial plan was to have something that would be generic enough to be able to handle most languages adequately. Unfortunately even with languages that are quite similar (C and C++) the differences were large enough to warrant separate handlers for each language.

But I do agree that  "Major mode not supported" is rather ugly, and maybe your suggestion to default to a rudimentary handler that simply lists available nodes and their preview text might be better than nothing.

Let me think about this :)

**Comment by Giedriusj1** [comment]
Alright, I've changed how the main helm-tree-sitter function works. When it encounters major mode it does not understand, it'll default to listing all existing nodes, with a view very similar to the one you suggested.

I hope you find this useful!
